project_id: "395009"
api_token_env: CROWDIN_PERSONAL_TOKEN
commit_message: "chore(i18n): translations for %original_file_name% (%language%)"
pull_request_title: "chore(i18n): update localization files"
append_commit_message: false
files:
  - source: /src/languages/en-US/**/*.json
    translation: /src/languages/%locale%/**/%original_file_name%
