version: "3.5"

services:
    mongo:
        container_name: "mongo"
        image: mongo
        restart: always
        networks:
            - payload
        ports:
            - 27017-27019:27017-27019
        volumes:
            - mongo:/data/db
        env_file:
            - ./.env

    nginx:
        container_name: "nginx"
        image: nginx:1-alpine
        restart: always
        networks:
            - payload
        ports:
            - 80:80
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        env_file:
            - ./.env
        depends_on:
            - payload

    redis:
        container_name: "redis"
        image: redis:alpine
        networks:
            - payload
        restart: always
        ports:
            - 6379:6379

    chrome:
        container_name: "chrome"
        image: browserless/chrome
        networks:
            - payload
        environment:
            - MAX_CONCURRENT_SESSIONS=10
            - PORT=9090
            - ENABLE_DEBUGGER=false
            - EXIT_ON_HEALTH_FAILURE=true
            - DEBUG=-*
        ports: 
            - 9090:9090
        restart: always

    payload:
        build: .
        container_name: "payload"
        command: "npm start"
        restart: always
        networks:
            - payload
        env_file:
            - ./.env
        ports:
            - 3000:3000
        depends_on:
            - mongo
            - redis
        links:
            - mongo
            - redis
            - chrome

volumes:
    mongo: ~

networks:
    payload:
