version: "3.5"

services:
    chrome:
        container_name: "chrome"
        image: browserless/chrome
        networks:
            - bot_internal
        environment:
            - MAX_CONCURRENT_SESSIONS=10
            - PORT=9090
            - ENABLE_DEBUGGER=false
            - EXIT_ON_HEALTH_FAILURE=true
            - DEBUG=-*
        ports: 
            - 9090:9090
        restart: always

    payload:
        build: .
        container_name: "payload"
        command: "yarn start"
        restart: always
        networks:
            - bot_internal
        env_file:
            - ./.env
        ports:
            - 9091:9091
        depends_on:
            - chrome
        links:
            - chrome

networks:
    bot_internal:
