app = "payload"
primary_region = "ord"
kill_signal = "SIGINT"
kill_timeout = "5s"

[metrics]
  port = 3000
  path = "/api/metrics"

[env]
  CHROME_WS_ENABLE = "false"
  CHROME_WS_URL = ""
  OWNERS = "176457969465163776"
  PORT = "3000"
  ENVIRONMENT = "production"

[[mounts]]
  source = "data"
  destination = "/data"

[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0
